### ISSUE TITLE
pg-sql2

### ISSUE THREAD

**Issue by streamich** [sequencework/sql#14]
Have you seen `pg-sql2`? Just wondering how it compares to this lib?

**Comment by lucleray** [comment]
I didn't know `pg-sql2`, thanks for sharing.

I would say this library is smaller. And we have some [nice shortcuts for pg](https://github.com/sequencework/sql#shorthand-for-postgres) 

Is there something from pg-sql2 that you would like to see here ?

(I also want to add benchmarks in the near future to compare how fast this is to other libraries, I'll add pg-sql2 to the list 🙂)

**Comment by streamich** [comment]
> Is there something from pg-sql2 that you would like to see here?

Have not tried this lib yet, will give it a go next week.

**Comment by lucleray** [comment]
Sure, let me know what you think 🙂
